n = int(input("Escreva um número:"))
print("O dobro de {} vale {}".format(n, (n*2)))
print("O tripo de {} vale {}".format(n, (n*3)))
print("A raiz quadrada de {} é igual a {:.2f}".format(n, (n**(1/2))))
print("A raiz quadrada de {} é igual a {:.2f}".format(n, pow(n, (1/2))))
