texto = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
textoma = texto.upper()
print('Seu nome em maiúsculas é {}'.format(textoma))
textomi = texto.lower()
print('Seu nome em minusculas é {}'.format(textomi))
textonu = len(texto) - texto.count(' ')
print('Seu nome tem ao todo {} letras'.format(textonu))
textoco = texto.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(textoco[0], len(textoco[0])))