n = str(input('Digite seu nome completo: ')).strip()
print('Muito prazer em te conhecer {}!'.format(n.split()[0]))
nome = n.split()
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu último nome é {}'.format(nome[len(nome)-1]))